/** Colonnes des fichiers RPPS « libre accès » : [nom SQL, libellé exact dans l'en-tête].
 *
 *  L'import compare l'en-tête réel du fichier à cette liste, dans l'ordre : si le
 *  producteur (ANS) ajoute, retire ou réordonne une colonne, l'import s'arrête net avec
 *  un message clair — jamais de décalage silencieux qui rangerait un téléphone dans une
 *  colonne e-mail. */
export type ColumnSpec = readonly (readonly [sql: string, header: string])[]

export const ACTIVITE_COLUMNS: ColumnSpec = [
  ['type_id_pp', "Type d'identifiant PP"],
  ['id_pp', 'Identifiant PP'],
  ['id_national', 'Identification nationale PP'],
  ['code_civilite_exercice', "Code civilité d'exercice"],
  ['civilite_exercice', "Libellé civilité d'exercice"],
  ['code_civilite', 'Code civilité'],
  ['civilite', 'Libellé civilité'],
  ['nom', "Nom d'exercice"],
  ['prenom', "Prénom d'exercice"],
  ['code_profession', 'Code profession'],
  ['profession', 'Libellé profession'],
  ['code_categorie', 'Code catégorie professionnelle'],
  ['categorie', 'Libellé catégorie professionnelle'],
  ['code_type_savoir_faire', 'Code type savoir-faire'],
  ['type_savoir_faire', 'Libellé type savoir-faire'],
  ['code_savoir_faire', 'Code savoir-faire'],
  ['savoir_faire', 'Libellé savoir-faire'],
  ['code_mode_exercice', 'Code mode exercice'],
  ['mode_exercice', 'Libellé mode exercice'],
  ['siret', 'Numéro SIRET site'],
  ['siren', 'Numéro SIREN site'],
  ['finess_site', 'Numéro FINESS site'],
  ['finess_ej', 'Numéro FINESS établissement juridique'],
  ['id_structure', 'Identifiant technique de la structure'],
  ['raison_sociale', 'Raison sociale site'],
  ['enseigne', 'Enseigne commerciale site'],
  ['complement_destinataire', 'Complément destinataire (coord. structure)'],
  ['complement_geo', 'Complément point géographique (coord. structure)'],
  ['num_voie', 'Numéro Voie (coord. structure)'],
  ['indice_voie', 'Indice répétition voie (coord. structure)'],
  ['code_type_voie', 'Code type de voie (coord. structure)'],
  ['type_voie', 'Libellé type de voie (coord. structure)'],
  ['libelle_voie', 'Libellé Voie (coord. structure)'],
  ['mention_distribution', 'Mention distribution (coord. structure)'],
  ['bureau_cedex', 'Bureau cedex (coord. structure)'],
  ['code_postal', 'Code postal (coord. structure)'],
  ['code_commune', 'Code commune (coord. structure)'],
  ['commune', 'Libellé commune (coord. structure)'],
  ['code_pays', 'Code pays (coord. structure)'],
  ['pays', 'Libellé pays (coord. structure)'],
  ['telephone', 'Téléphone (coord. structure)'],
  ['telephone2', 'Téléphone 2 (coord. structure)'],
  ['telecopie', 'Télécopie (coord. structure)'],
  ['email', 'Adresse e-mail (coord. structure)'],
  ['code_departement', 'Code Département (structure)'],
  ['departement', 'Libellé Département (structure)'],
  ['ancien_id_structure', 'Ancien identifiant de la structure'],
  ['autorite_enregistrement', "Autorité d'enregistrement"],
  ['code_secteur', "Code secteur d'activité"],
  ['secteur', "Libellé secteur d'activité"],
  ['code_section_pharmaciens', 'Code section tableau pharmaciens'],
  ['section_pharmaciens', 'Libellé section tableau pharmaciens'],
  ['code_role', 'Code rôle'],
  ['role', 'Libellé rôle'],
  ['code_genre_activite', 'Code genre activité'],
  ['genre_activite', 'Libellé genre activité'],
]

export const DIPLOME_COLUMNS: ColumnSpec = [
  ['type_id_pp', "Type d'identifiant PP"],
  ['id_pp', 'Identifiant PP'],
  ['id_national', 'Identification nationale PP'],
  ['nom', "Nom d'exercice"],
  ['prenom', "Prénom d'exercice"],
  ['code_type_diplome', 'Code type diplôme obtenu'],
  ['type_diplome', 'Libellé type diplôme obtenu'],
  ['code_diplome', 'Code diplôme obtenu'],
  ['diplome', 'Libellé diplôme obtenu'],
  ['code_type_autorisation', 'Code type autorisation'],
  ['type_autorisation', 'Libellé type autorisation'],
  ['code_discipline_autorisation', 'Code discipline autorisation'],
  ['discipline_autorisation', 'Libellé discipline autorisation'],
]

export const SAVOIR_FAIRE_COLUMNS: ColumnSpec = [
  ['type_id_pp', "Type d'identifiant PP"],
  ['id_pp', 'Identifiant PP'],
  ['id_national', 'Identification nationale PP'],
  ['nom', "Nom d'exercice"],
  ['prenom', "Prénom d'exercice"],
  ['code_profession', 'Code profession'],
  ['profession', 'Libellé profession'],
  ['code_categorie', 'Code catégorie professionnelle'],
  ['categorie', 'Libellé catégorie professionnelle'],
  ['code_type_savoir_faire', 'Code type savoir-faire'],
  ['type_savoir_faire', 'Libellé type savoir-faire'],
  ['code_savoir_faire', 'Code savoir-faire'],
  ['savoir_faire', 'Libellé savoir-faire'],
]
